<?php 
return [
'name' => 'Saporis',
'map' => 'Av.26 De Enero Mza. B Lt 08- Huamanga- Ayacucho',
'website' => '#',
'company_phone' => '914950869',
'email_from' => 'eyner200@gmail.com',
'maintenance_mode' => '1',
'currency' => 'S/',
'shop_min_amount' => '100',
'shipping_method' => '1',
'shipping_default_value' => '40',
'shipping_amount_min' => '500',
'to_go' => '1',
'facebook' => 'https://www.facebook.com/saporis.catering/',
'instagram' => 'https://www.instagram.com/sapori.service/',
'twitter' => '',
'twitter' => '',
'youtube' => '',
'youtube' => '',
'whatsapp' => 'https://wa.me/51914950869?text=Hola,%20necesito%20información',
'payment_method_cash' => '1',
'payment_method_creditcard' => '0',
'payment_method_transfer' => '1',
'payment_method_transfer_accounts_bank_BCP' => '',
'payment_method_transfer_accounts_bank_BCP' => '',
'payment_method_transfer_accounts_bank_BCPCCI' => '',
'payment_method_transfer_accounts_bank_BCPCCI' => '',
'payment_method_transfer_accounts_bank_BBVA' => '',
'payment_method_transfer_accounts_bank_BBVA' => '',
'payment_method_transfer_accounts_bank_BBVACCI' => '',
'payment_method_transfer_accounts_bank_BBVACCI' => '',
'payment_method_paypal' => '0',
'payment_method_yape' => '1',
'server_uploads_paths' => './uploads',
'server_uploads_user_paths' => './uploads_users',
'server_webapp_path' => '',
'server_webapp_path' => '',
'products_per_page' => '5',
'products_per_page_random' => '10',
]
?>
